//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MISInterfaceDAL.UploadPickInfo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FEPV_GetSOInfoSoap", Namespace="http://tempuri.org/")]
    public partial class FEPV_GetSOInfo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback zFEPV_ZSDO2701_SO_INFOOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadSOInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadStockInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadStockInfo_ChemicalOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEstPackingInfo_SSPOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEstPackingInfo_SSPBySONOOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadStockInfo_TestAteamOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendATeamMSGOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendATeamMSG2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FEPV_GetSOInfo() {
            this.Url = global::MISInterfaceDAL.Properties.Settings.Default.MISInterfaceDAL_UploadPickInfo_FEPV_GetSOInfo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event zFEPV_ZSDO2701_SO_INFOCompletedEventHandler zFEPV_ZSDO2701_SO_INFOCompleted;
        
        /// <remarks/>
        public event UploadSOInfoCompletedEventHandler UploadSOInfoCompleted;
        
        /// <remarks/>
        public event UploadStockInfoCompletedEventHandler UploadStockInfoCompleted;
        
        /// <remarks/>
        public event UploadStockInfo_ChemicalCompletedEventHandler UploadStockInfo_ChemicalCompleted;
        
        /// <remarks/>
        public event GetEstPackingInfo_SSPCompletedEventHandler GetEstPackingInfo_SSPCompleted;
        
        /// <remarks/>
        public event GetEstPackingInfo_SSPBySONOCompletedEventHandler GetEstPackingInfo_SSPBySONOCompleted;
        
        /// <remarks/>
        public event UploadStockInfo_TestAteamCompletedEventHandler UploadStockInfo_TestAteamCompleted;
        
        /// <remarks/>
        public event SendATeamMSGCompletedEventHandler SendATeamMSGCompleted;
        
        /// <remarks/>
        public event SendATeamMSG2CompletedEventHandler SendATeamMSG2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/zFEPV_ZSDO2701_SO_INFO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void zFEPV_ZSDO2701_SO_INFO(Base_Table basetableList, T_SDHEADER[] T_SDHEADER, T_SDITEMS[] T_SDITEMS, int EP_SUCC, string EP_MESS) {
            this.Invoke("zFEPV_ZSDO2701_SO_INFO", new object[] {
                        basetableList,
                        T_SDHEADER,
                        T_SDITEMS,
                        EP_SUCC,
                        EP_MESS});
        }
        
        /// <remarks/>
        public void zFEPV_ZSDO2701_SO_INFOAsync(Base_Table basetableList, T_SDHEADER[] T_SDHEADER, T_SDITEMS[] T_SDITEMS, int EP_SUCC, string EP_MESS) {
            this.zFEPV_ZSDO2701_SO_INFOAsync(basetableList, T_SDHEADER, T_SDITEMS, EP_SUCC, EP_MESS, null);
        }
        
        /// <remarks/>
        public void zFEPV_ZSDO2701_SO_INFOAsync(Base_Table basetableList, T_SDHEADER[] T_SDHEADER, T_SDITEMS[] T_SDITEMS, int EP_SUCC, string EP_MESS, object userState) {
            if ((this.zFEPV_ZSDO2701_SO_INFOOperationCompleted == null)) {
                this.zFEPV_ZSDO2701_SO_INFOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnzFEPV_ZSDO2701_SO_INFOOperationCompleted);
            }
            this.InvokeAsync("zFEPV_ZSDO2701_SO_INFO", new object[] {
                        basetableList,
                        T_SDHEADER,
                        T_SDITEMS,
                        EP_SUCC,
                        EP_MESS}, this.zFEPV_ZSDO2701_SO_INFOOperationCompleted, userState);
        }
        
        private void OnzFEPV_ZSDO2701_SO_INFOOperationCompleted(object arg) {
            if ((this.zFEPV_ZSDO2701_SO_INFOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.zFEPV_ZSDO2701_SO_INFOCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadSOInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet UploadSOInfo(System.Data.DataSet ds) {
            object[] results = this.Invoke("UploadSOInfo", new object[] {
                        ds});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void UploadSOInfoAsync(System.Data.DataSet ds) {
            this.UploadSOInfoAsync(ds, null);
        }
        
        /// <remarks/>
        public void UploadSOInfoAsync(System.Data.DataSet ds, object userState) {
            if ((this.UploadSOInfoOperationCompleted == null)) {
                this.UploadSOInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadSOInfoOperationCompleted);
            }
            this.InvokeAsync("UploadSOInfo", new object[] {
                        ds}, this.UploadSOInfoOperationCompleted, userState);
        }
        
        private void OnUploadSOInfoOperationCompleted(object arg) {
            if ((this.UploadSOInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadSOInfoCompleted(this, new UploadSOInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadStockInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet UploadStockInfo(System.Data.DataSet ds) {
            object[] results = this.Invoke("UploadStockInfo", new object[] {
                        ds});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void UploadStockInfoAsync(System.Data.DataSet ds) {
            this.UploadStockInfoAsync(ds, null);
        }
        
        /// <remarks/>
        public void UploadStockInfoAsync(System.Data.DataSet ds, object userState) {
            if ((this.UploadStockInfoOperationCompleted == null)) {
                this.UploadStockInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadStockInfoOperationCompleted);
            }
            this.InvokeAsync("UploadStockInfo", new object[] {
                        ds}, this.UploadStockInfoOperationCompleted, userState);
        }
        
        private void OnUploadStockInfoOperationCompleted(object arg) {
            if ((this.UploadStockInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadStockInfoCompleted(this, new UploadStockInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadStockInfo_Chemical", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet UploadStockInfo_Chemical(System.Data.DataSet ds) {
            object[] results = this.Invoke("UploadStockInfo_Chemical", new object[] {
                        ds});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void UploadStockInfo_ChemicalAsync(System.Data.DataSet ds) {
            this.UploadStockInfo_ChemicalAsync(ds, null);
        }
        
        /// <remarks/>
        public void UploadStockInfo_ChemicalAsync(System.Data.DataSet ds, object userState) {
            if ((this.UploadStockInfo_ChemicalOperationCompleted == null)) {
                this.UploadStockInfo_ChemicalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadStockInfo_ChemicalOperationCompleted);
            }
            this.InvokeAsync("UploadStockInfo_Chemical", new object[] {
                        ds}, this.UploadStockInfo_ChemicalOperationCompleted, userState);
        }
        
        private void OnUploadStockInfo_ChemicalOperationCompleted(object arg) {
            if ((this.UploadStockInfo_ChemicalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadStockInfo_ChemicalCompleted(this, new UploadStockInfo_ChemicalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEstPackingInfo_SSP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetEstPackingInfo_SSP(System.Data.DataSet ds) {
            object[] results = this.Invoke("GetEstPackingInfo_SSP", new object[] {
                        ds});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetEstPackingInfo_SSPAsync(System.Data.DataSet ds) {
            this.GetEstPackingInfo_SSPAsync(ds, null);
        }
        
        /// <remarks/>
        public void GetEstPackingInfo_SSPAsync(System.Data.DataSet ds, object userState) {
            if ((this.GetEstPackingInfo_SSPOperationCompleted == null)) {
                this.GetEstPackingInfo_SSPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEstPackingInfo_SSPOperationCompleted);
            }
            this.InvokeAsync("GetEstPackingInfo_SSP", new object[] {
                        ds}, this.GetEstPackingInfo_SSPOperationCompleted, userState);
        }
        
        private void OnGetEstPackingInfo_SSPOperationCompleted(object arg) {
            if ((this.GetEstPackingInfo_SSPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEstPackingInfo_SSPCompleted(this, new GetEstPackingInfo_SSPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEstPackingInfo_SSPBySONO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetEstPackingInfo_SSPBySONO(System.Data.DataSet ds) {
            object[] results = this.Invoke("GetEstPackingInfo_SSPBySONO", new object[] {
                        ds});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetEstPackingInfo_SSPBySONOAsync(System.Data.DataSet ds) {
            this.GetEstPackingInfo_SSPBySONOAsync(ds, null);
        }
        
        /// <remarks/>
        public void GetEstPackingInfo_SSPBySONOAsync(System.Data.DataSet ds, object userState) {
            if ((this.GetEstPackingInfo_SSPBySONOOperationCompleted == null)) {
                this.GetEstPackingInfo_SSPBySONOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEstPackingInfo_SSPBySONOOperationCompleted);
            }
            this.InvokeAsync("GetEstPackingInfo_SSPBySONO", new object[] {
                        ds}, this.GetEstPackingInfo_SSPBySONOOperationCompleted, userState);
        }
        
        private void OnGetEstPackingInfo_SSPBySONOOperationCompleted(object arg) {
            if ((this.GetEstPackingInfo_SSPBySONOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEstPackingInfo_SSPBySONOCompleted(this, new GetEstPackingInfo_SSPBySONOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadStockInfo_TestAteam", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet UploadStockInfo_TestAteam(System.Data.DataSet ds) {
            object[] results = this.Invoke("UploadStockInfo_TestAteam", new object[] {
                        ds});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void UploadStockInfo_TestAteamAsync(System.Data.DataSet ds) {
            this.UploadStockInfo_TestAteamAsync(ds, null);
        }
        
        /// <remarks/>
        public void UploadStockInfo_TestAteamAsync(System.Data.DataSet ds, object userState) {
            if ((this.UploadStockInfo_TestAteamOperationCompleted == null)) {
                this.UploadStockInfo_TestAteamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadStockInfo_TestAteamOperationCompleted);
            }
            this.InvokeAsync("UploadStockInfo_TestAteam", new object[] {
                        ds}, this.UploadStockInfo_TestAteamOperationCompleted, userState);
        }
        
        private void OnUploadStockInfo_TestAteamOperationCompleted(object arg) {
            if ((this.UploadStockInfo_TestAteamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadStockInfo_TestAteamCompleted(this, new UploadStockInfo_TestAteamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendATeamMSG", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendATeamMSG(System.Data.DataSet ds) {
            this.Invoke("SendATeamMSG", new object[] {
                        ds});
        }
        
        /// <remarks/>
        public void SendATeamMSGAsync(System.Data.DataSet ds) {
            this.SendATeamMSGAsync(ds, null);
        }
        
        /// <remarks/>
        public void SendATeamMSGAsync(System.Data.DataSet ds, object userState) {
            if ((this.SendATeamMSGOperationCompleted == null)) {
                this.SendATeamMSGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendATeamMSGOperationCompleted);
            }
            this.InvokeAsync("SendATeamMSG", new object[] {
                        ds}, this.SendATeamMSGOperationCompleted, userState);
        }
        
        private void OnSendATeamMSGOperationCompleted(object arg) {
            if ((this.SendATeamMSGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendATeamMSGCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendATeamMSG2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendATeamMSG2(System.Data.DataSet ds, string SystemCode, string AcceptUserIDS, string MessagePart1, string MessagePart2, string SystemDescription, string CompanyCode, string MessageTypeCode, string MessageTypeDescription) {
            this.Invoke("SendATeamMSG2", new object[] {
                        ds,
                        SystemCode,
                        AcceptUserIDS,
                        MessagePart1,
                        MessagePart2,
                        SystemDescription,
                        CompanyCode,
                        MessageTypeCode,
                        MessageTypeDescription});
        }
        
        /// <remarks/>
        public void SendATeamMSG2Async(System.Data.DataSet ds, string SystemCode, string AcceptUserIDS, string MessagePart1, string MessagePart2, string SystemDescription, string CompanyCode, string MessageTypeCode, string MessageTypeDescription) {
            this.SendATeamMSG2Async(ds, SystemCode, AcceptUserIDS, MessagePart1, MessagePart2, SystemDescription, CompanyCode, MessageTypeCode, MessageTypeDescription, null);
        }
        
        /// <remarks/>
        public void SendATeamMSG2Async(System.Data.DataSet ds, string SystemCode, string AcceptUserIDS, string MessagePart1, string MessagePart2, string SystemDescription, string CompanyCode, string MessageTypeCode, string MessageTypeDescription, object userState) {
            if ((this.SendATeamMSG2OperationCompleted == null)) {
                this.SendATeamMSG2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendATeamMSG2OperationCompleted);
            }
            this.InvokeAsync("SendATeamMSG2", new object[] {
                        ds,
                        SystemCode,
                        AcceptUserIDS,
                        MessagePart1,
                        MessagePart2,
                        SystemDescription,
                        CompanyCode,
                        MessageTypeCode,
                        MessageTypeDescription}, this.SendATeamMSG2OperationCompleted, userState);
        }
        
        private void OnSendATeamMSG2OperationCompleted(object arg) {
            if ((this.SendATeamMSG2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendATeamMSG2Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Base_Table {
        
        private string mESSAGEIDField;
        
        private string mESSAGETEXTField;
        
        private string mESSAGETYPEField;
        
        private string sENDTIMEField;
        
        private string tOKENField;
        
        private string fROMSYSIDField;
        
        private string tOSYSIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MESSAGEID {
            get {
                return this.mESSAGEIDField;
            }
            set {
                this.mESSAGEIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MESSAGETEXT {
            get {
                return this.mESSAGETEXTField;
            }
            set {
                this.mESSAGETEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MESSAGETYPE {
            get {
                return this.mESSAGETYPEField;
            }
            set {
                this.mESSAGETYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SENDTIME {
            get {
                return this.sENDTIMEField;
            }
            set {
                this.sENDTIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TOKEN {
            get {
                return this.tOKENField;
            }
            set {
                this.tOKENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FROMSYSID {
            get {
                return this.fROMSYSIDField;
            }
            set {
                this.fROMSYSIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TOSYSID {
            get {
                return this.tOSYSIDField;
            }
            set {
                this.tOSYSIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class T_SDITEMS {
        
        private string vBELNField;
        
        private string pOSNRField;
        
        private string wERKSField;
        
        private string mATWAField;
        
        private string aRKTXField;
        
        private decimal kBETR_BGField;
        
        private string kOEIN_BGField;
        
        private decimal kPEIN_BGField;
        
        private string kMEIN_BGField;
        
        private decimal kWERT_BGField;
        
        private string wAERK_BGField;
        
        private decimal kBET1_BGField;
        
        private string kOEI1_BGField;
        
        private decimal kUMNE_BGField;
        
        private string mEINS_BGField;
        
        private decimal kBETR_YHField;
        
        private string kOEIN_YHField;
        
        private decimal kPEIN_YHField;
        
        private string kMEIN_YHField;
        
        private decimal kWERT_YHField;
        
        private string wAERK_YHField;
        
        private decimal uMVKN1Field;
        
        private string vRKME1Field;
        
        private decimal uMVKZ1Field;
        
        private string mEINS1Field;
        
        private decimal kWMENGField;
        
        private string vRKMEField;
        
        private decimal nTGEWField;
        
        private decimal bRGEWField;
        
        private string gEWEIField;
        
        private decimal vOLUMField;
        
        private string vOLEHField;
        
        private string cHARGField;
        
        private decimal uEBTOField;
        
        private decimal uNTTOField;
        
        private string aESKDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VBELN {
            get {
                return this.vBELNField;
            }
            set {
                this.vBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string POSNR {
            get {
                return this.pOSNRField;
            }
            set {
                this.pOSNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MATWA {
            get {
                return this.mATWAField;
            }
            set {
                this.mATWAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ARKTX {
            get {
                return this.aRKTXField;
            }
            set {
                this.aRKTXField = value;
            }
        }
        
        /// <remarks/>
        public decimal KBETR_BG {
            get {
                return this.kBETR_BGField;
            }
            set {
                this.kBETR_BGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string KOEIN_BG {
            get {
                return this.kOEIN_BGField;
            }
            set {
                this.kOEIN_BGField = value;
            }
        }
        
        /// <remarks/>
        public decimal KPEIN_BG {
            get {
                return this.kPEIN_BGField;
            }
            set {
                this.kPEIN_BGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string KMEIN_BG {
            get {
                return this.kMEIN_BGField;
            }
            set {
                this.kMEIN_BGField = value;
            }
        }
        
        /// <remarks/>
        public decimal KWERT_BG {
            get {
                return this.kWERT_BGField;
            }
            set {
                this.kWERT_BGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WAERK_BG {
            get {
                return this.wAERK_BGField;
            }
            set {
                this.wAERK_BGField = value;
            }
        }
        
        /// <remarks/>
        public decimal KBET1_BG {
            get {
                return this.kBET1_BGField;
            }
            set {
                this.kBET1_BGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string KOEI1_BG {
            get {
                return this.kOEI1_BGField;
            }
            set {
                this.kOEI1_BGField = value;
            }
        }
        
        /// <remarks/>
        public decimal KUMNE_BG {
            get {
                return this.kUMNE_BGField;
            }
            set {
                this.kUMNE_BGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MEINS_BG {
            get {
                return this.mEINS_BGField;
            }
            set {
                this.mEINS_BGField = value;
            }
        }
        
        /// <remarks/>
        public decimal KBETR_YH {
            get {
                return this.kBETR_YHField;
            }
            set {
                this.kBETR_YHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string KOEIN_YH {
            get {
                return this.kOEIN_YHField;
            }
            set {
                this.kOEIN_YHField = value;
            }
        }
        
        /// <remarks/>
        public decimal KPEIN_YH {
            get {
                return this.kPEIN_YHField;
            }
            set {
                this.kPEIN_YHField = value;
            }
        }
        
        /// <remarks/>
        public string KMEIN_YH {
            get {
                return this.kMEIN_YHField;
            }
            set {
                this.kMEIN_YHField = value;
            }
        }
        
        /// <remarks/>
        public decimal KWERT_YH {
            get {
                return this.kWERT_YHField;
            }
            set {
                this.kWERT_YHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WAERK_YH {
            get {
                return this.wAERK_YHField;
            }
            set {
                this.wAERK_YHField = value;
            }
        }
        
        /// <remarks/>
        public decimal UMVKN1 {
            get {
                return this.uMVKN1Field;
            }
            set {
                this.uMVKN1Field = value;
            }
        }
        
        /// <remarks/>
        public string VRKME1 {
            get {
                return this.vRKME1Field;
            }
            set {
                this.vRKME1Field = value;
            }
        }
        
        /// <remarks/>
        public decimal UMVKZ1 {
            get {
                return this.uMVKZ1Field;
            }
            set {
                this.uMVKZ1Field = value;
            }
        }
        
        /// <remarks/>
        public string MEINS1 {
            get {
                return this.mEINS1Field;
            }
            set {
                this.mEINS1Field = value;
            }
        }
        
        /// <remarks/>
        public decimal KWMENG {
            get {
                return this.kWMENGField;
            }
            set {
                this.kWMENGField = value;
            }
        }
        
        /// <remarks/>
        public string VRKME {
            get {
                return this.vRKMEField;
            }
            set {
                this.vRKMEField = value;
            }
        }
        
        /// <remarks/>
        public decimal NTGEW {
            get {
                return this.nTGEWField;
            }
            set {
                this.nTGEWField = value;
            }
        }
        
        /// <remarks/>
        public decimal BRGEW {
            get {
                return this.bRGEWField;
            }
            set {
                this.bRGEWField = value;
            }
        }
        
        /// <remarks/>
        public string GEWEI {
            get {
                return this.gEWEIField;
            }
            set {
                this.gEWEIField = value;
            }
        }
        
        /// <remarks/>
        public decimal VOLUM {
            get {
                return this.vOLUMField;
            }
            set {
                this.vOLUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VOLEH {
            get {
                return this.vOLEHField;
            }
            set {
                this.vOLEHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CHARG {
            get {
                return this.cHARGField;
            }
            set {
                this.cHARGField = value;
            }
        }
        
        /// <remarks/>
        public decimal UEBTO {
            get {
                return this.uEBTOField;
            }
            set {
                this.uEBTOField = value;
            }
        }
        
        /// <remarks/>
        public decimal UNTTO {
            get {
                return this.uNTTOField;
            }
            set {
                this.uNTTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AESKD {
            get {
                return this.aESKDField;
            }
            set {
                this.aESKDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class T_SDHEADER {
        
        private string vBELNField;
        
        private string aUARTField;
        
        private string bUKRSField;
        
        private string vKORGField;
        
        private string vTWEGField;
        
        private string sPARTField;
        
        private string kUNNR1Field;
        
        private string tXTPA1Field;
        
        private string kUNNR2Field;
        
        private string tXTPA2Field;
        
        private string kOSTLField;
        
        private decimal kWMENG_TField;
        
        private string vRKMEField;
        
        private string wAERKField;
        
        private decimal kURSKField;
        
        private string tRMTYPField;
        
        private string bEZEIField;
        
        private string vKGRPField;
        
        private string iNCO1Field;
        
        private string iNCO2Field;
        
        private string vTEXTField;
        
        private string pARVWField;
        
        private string zTERMField;
        
        private string eRDATField;
        
        private string pRCTRField;
        
        private string kETDATField;
        
        private string vSBEDField;
        
        private string tRATYField;
        
        private string bSTKDField;
        
        private string lAND1Field;
        
        private string zTYPEField;
        
        private string sTATEField;
        
        private string dELField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VBELN {
            get {
                return this.vBELNField;
            }
            set {
                this.vBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AUART {
            get {
                return this.aUARTField;
            }
            set {
                this.aUARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VKORG {
            get {
                return this.vKORGField;
            }
            set {
                this.vKORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VTWEG {
            get {
                return this.vTWEGField;
            }
            set {
                this.vTWEGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SPART {
            get {
                return this.sPARTField;
            }
            set {
                this.sPARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string KUNNR1 {
            get {
                return this.kUNNR1Field;
            }
            set {
                this.kUNNR1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TXTPA1 {
            get {
                return this.tXTPA1Field;
            }
            set {
                this.tXTPA1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string KUNNR2 {
            get {
                return this.kUNNR2Field;
            }
            set {
                this.kUNNR2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TXTPA2 {
            get {
                return this.tXTPA2Field;
            }
            set {
                this.tXTPA2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string KOSTL {
            get {
                return this.kOSTLField;
            }
            set {
                this.kOSTLField = value;
            }
        }
        
        /// <remarks/>
        public decimal KWMENG_T {
            get {
                return this.kWMENG_TField;
            }
            set {
                this.kWMENG_TField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VRKME {
            get {
                return this.vRKMEField;
            }
            set {
                this.vRKMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WAERK {
            get {
                return this.wAERKField;
            }
            set {
                this.wAERKField = value;
            }
        }
        
        /// <remarks/>
        public decimal KURSK {
            get {
                return this.kURSKField;
            }
            set {
                this.kURSKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TRMTYP {
            get {
                return this.tRMTYPField;
            }
            set {
                this.tRMTYPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BEZEI {
            get {
                return this.bEZEIField;
            }
            set {
                this.bEZEIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VKGRP {
            get {
                return this.vKGRPField;
            }
            set {
                this.vKGRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string INCO1 {
            get {
                return this.iNCO1Field;
            }
            set {
                this.iNCO1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string INCO2 {
            get {
                return this.iNCO2Field;
            }
            set {
                this.iNCO2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VTEXT {
            get {
                return this.vTEXTField;
            }
            set {
                this.vTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PARVW {
            get {
                return this.pARVWField;
            }
            set {
                this.pARVWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ZTERM {
            get {
                return this.zTERMField;
            }
            set {
                this.zTERMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ERDAT {
            get {
                return this.eRDATField;
            }
            set {
                this.eRDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PRCTR {
            get {
                return this.pRCTRField;
            }
            set {
                this.pRCTRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string KETDAT {
            get {
                return this.kETDATField;
            }
            set {
                this.kETDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VSBED {
            get {
                return this.vSBEDField;
            }
            set {
                this.vSBEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TRATY {
            get {
                return this.tRATYField;
            }
            set {
                this.tRATYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BSTKD {
            get {
                return this.bSTKDField;
            }
            set {
                this.bSTKDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LAND1 {
            get {
                return this.lAND1Field;
            }
            set {
                this.lAND1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ZTYPE {
            get {
                return this.zTYPEField;
            }
            set {
                this.zTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string STATE {
            get {
                return this.sTATEField;
            }
            set {
                this.sTATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DEL {
            get {
                return this.dELField;
            }
            set {
                this.dELField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void zFEPV_ZSDO2701_SO_INFOCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void UploadSOInfoCompletedEventHandler(object sender, UploadSOInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadSOInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadSOInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void UploadStockInfoCompletedEventHandler(object sender, UploadStockInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadStockInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadStockInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void UploadStockInfo_ChemicalCompletedEventHandler(object sender, UploadStockInfo_ChemicalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadStockInfo_ChemicalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadStockInfo_ChemicalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetEstPackingInfo_SSPCompletedEventHandler(object sender, GetEstPackingInfo_SSPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEstPackingInfo_SSPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEstPackingInfo_SSPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetEstPackingInfo_SSPBySONOCompletedEventHandler(object sender, GetEstPackingInfo_SSPBySONOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEstPackingInfo_SSPBySONOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEstPackingInfo_SSPBySONOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void UploadStockInfo_TestAteamCompletedEventHandler(object sender, UploadStockInfo_TestAteamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadStockInfo_TestAteamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadStockInfo_TestAteamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SendATeamMSGCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SendATeamMSG2CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591