//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEPVWebApiOwinHost.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.2.31.1/A27N6Service/WA27N6Connect/WA27N6MIS001.asmx")]
        public string FEPVWebApiOwinHost_GetShippingOrder_WA27N6MIS001 {
            get {
                return ((string)(this["FEPVWebApiOwinHost_GetShippingOrder_WA27N6MIS001"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.2.31.1/A27N6Service/WA27N6Connect/WA27N6MIS002.asmx")]
        public string FEPVWebApiOwinHost_WebReference_WA27N6MIS002 {
            get {
                return ((string)(this["FEPVWebApiOwinHost_WebReference_WA27N6MIS002"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.2.31.1/A27N6Service/WA27N6Connect/WA27N6MIS001.asmx")]
        public string FEPVWebApiOwinHost_ShippingOrderDate_WA27N6MIS001 {
            get {
                return ((string)(this["FEPVWebApiOwinHost_ShippingOrderDate_WA27N6MIS001"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.2.31.1/A27N6Service/WA27N6Connect/WA27N6MIS002.asmx")]
        public string FEPVWebApiOwinHost_VehicleInformationInput_WA27N6MIS002 {
            get {
                return ((string)(this["FEPVWebApiOwinHost_VehicleInformationInput_WA27N6MIS002"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.17.213.167:8006/ZFEPV_GetBLInfo.asmx")]
        public string FEPVWebApiOwinHost_VehicleTransfer_ZFEPV_GetBLInfo {
            get {
                return ((string)(this["FEPVWebApiOwinHost_VehicleTransfer_ZFEPV_GetBLInfo"]));
            }
        }
    }
}
