//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace HRMSInterfaceDAL.Hr_SuZhou_Service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceHRSoap", Namespace="http://tempuri.org/")]
    public partial class WebServiceHR : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetListProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListProfileThaCoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceHR() {
            this.Url = global::HRMSInterfaceDAL.Properties.Settings.Default.HRMSInterfaceDAL_Hr_SuZhou_Service_WebServiceHR;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetListProfileCompletedEventHandler GetListProfileCompleted;
        
        /// <remarks/>
        public event GetListProfileThaCoCompletedEventHandler GetListProfileThaCoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListProfile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HREmpInfoBean[] GetListProfile(string dateHireFrom, string dateHireTo, string dateUpdateFrom, string dateUpdateTo, string Status, string userLogin, string password) {
            object[] results = this.Invoke("GetListProfile", new object[] {
                        dateHireFrom,
                        dateHireTo,
                        dateUpdateFrom,
                        dateUpdateTo,
                        Status,
                        userLogin,
                        password});
            return ((HREmpInfoBean[])(results[0]));
        }
        
        /// <remarks/>
        public void GetListProfileAsync(string dateHireFrom, string dateHireTo, string dateUpdateFrom, string dateUpdateTo, string Status, string userLogin, string password) {
            this.GetListProfileAsync(dateHireFrom, dateHireTo, dateUpdateFrom, dateUpdateTo, Status, userLogin, password, null);
        }
        
        /// <remarks/>
        public void GetListProfileAsync(string dateHireFrom, string dateHireTo, string dateUpdateFrom, string dateUpdateTo, string Status, string userLogin, string password, object userState) {
            if ((this.GetListProfileOperationCompleted == null)) {
                this.GetListProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListProfileOperationCompleted);
            }
            this.InvokeAsync("GetListProfile", new object[] {
                        dateHireFrom,
                        dateHireTo,
                        dateUpdateFrom,
                        dateUpdateTo,
                        Status,
                        userLogin,
                        password}, this.GetListProfileOperationCompleted, userState);
        }
        
        private void OnGetListProfileOperationCompleted(object arg) {
            if ((this.GetListProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListProfileCompleted(this, new GetListProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListProfileThaCo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HREmpInfoBean[] GetListProfileThaCo(string datehirefrom, string datehireto, string updatedatefrom, string updatedateto, string userLogin, string password) {
            object[] results = this.Invoke("GetListProfileThaCo", new object[] {
                        datehirefrom,
                        datehireto,
                        updatedatefrom,
                        updatedateto,
                        userLogin,
                        password});
            return ((HREmpInfoBean[])(results[0]));
        }
        
        /// <remarks/>
        public void GetListProfileThaCoAsync(string datehirefrom, string datehireto, string updatedatefrom, string updatedateto, string userLogin, string password) {
            this.GetListProfileThaCoAsync(datehirefrom, datehireto, updatedatefrom, updatedateto, userLogin, password, null);
        }
        
        /// <remarks/>
        public void GetListProfileThaCoAsync(string datehirefrom, string datehireto, string updatedatefrom, string updatedateto, string userLogin, string password, object userState) {
            if ((this.GetListProfileThaCoOperationCompleted == null)) {
                this.GetListProfileThaCoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListProfileThaCoOperationCompleted);
            }
            this.InvokeAsync("GetListProfileThaCo", new object[] {
                        datehirefrom,
                        datehireto,
                        updatedatefrom,
                        updatedateto,
                        userLogin,
                        password}, this.GetListProfileThaCoOperationCompleted, userState);
        }
        
        private void OnGetListProfileThaCoOperationCompleted(object arg) {
            if ((this.GetListProfileThaCoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListProfileThaCoCompleted(this, new GetListProfileThaCoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HREmpInfoBean {
        
        private string totalRowField;
        
        private string companyCodeField;
        
        private string companyNameField;
        
        private string companyShortNameField;
        
        private string nameVNField;
        
        private string workNoField;
        
        private string nameCNField;
        
        private string nameENField;
        
        private string sexTypeField;
        
        private string iDNoField;
        
        private string birthdayField;
        
        private string cellPhoneNo_HomeField;
        
        private string cellPhoneNo_OfficeField;
        
        private string cellPhoneNo_MobileField;
        
        private string costCentreCodeField;
        
        private string costCentreNameField;
        
        private string costCentreNameCNField;
        
        private string emailField;
        
        private string positionCodeField;
        
        private string positionNameField;
        
        private string homeAddressField;
        
        private string statusField;
        
        private string bankAccountField;
        
        private string bankNameField;
        
        private string bankSwift_CodeField;
        
        private string cardNoField;
        
        private string departureDateField;
        
        private string joinDateField;
        
        private string countryField;
        
        private string passwordField;
        
        private string badListField;
        
        private string reasonOfBadListField;
        
        private string dateQuitField;
        
        private string dateUpdateField;
        
        private string workPlaceNameField;
        
        /// <remarks/>
        public string TotalRow {
            get {
                return this.totalRowField;
            }
            set {
                this.totalRowField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyShortName {
            get {
                return this.companyShortNameField;
            }
            set {
                this.companyShortNameField = value;
            }
        }
        
        /// <remarks/>
        public string NameVN {
            get {
                return this.nameVNField;
            }
            set {
                this.nameVNField = value;
            }
        }
        
        /// <remarks/>
        public string WorkNo {
            get {
                return this.workNoField;
            }
            set {
                this.workNoField = value;
            }
        }
        
        /// <remarks/>
        public string NameCN {
            get {
                return this.nameCNField;
            }
            set {
                this.nameCNField = value;
            }
        }
        
        /// <remarks/>
        public string NameEN {
            get {
                return this.nameENField;
            }
            set {
                this.nameENField = value;
            }
        }
        
        /// <remarks/>
        public string SexType {
            get {
                return this.sexTypeField;
            }
            set {
                this.sexTypeField = value;
            }
        }
        
        /// <remarks/>
        public string IDNo {
            get {
                return this.iDNoField;
            }
            set {
                this.iDNoField = value;
            }
        }
        
        /// <remarks/>
        public string Birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
            }
        }
        
        /// <remarks/>
        public string CellPhoneNo_Home {
            get {
                return this.cellPhoneNo_HomeField;
            }
            set {
                this.cellPhoneNo_HomeField = value;
            }
        }
        
        /// <remarks/>
        public string CellPhoneNo_Office {
            get {
                return this.cellPhoneNo_OfficeField;
            }
            set {
                this.cellPhoneNo_OfficeField = value;
            }
        }
        
        /// <remarks/>
        public string CellPhoneNo_Mobile {
            get {
                return this.cellPhoneNo_MobileField;
            }
            set {
                this.cellPhoneNo_MobileField = value;
            }
        }
        
        /// <remarks/>
        public string CostCentreCode {
            get {
                return this.costCentreCodeField;
            }
            set {
                this.costCentreCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CostCentreName {
            get {
                return this.costCentreNameField;
            }
            set {
                this.costCentreNameField = value;
            }
        }
        
        /// <remarks/>
        public string CostCentreNameCN {
            get {
                return this.costCentreNameCNField;
            }
            set {
                this.costCentreNameCNField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string PositionCode {
            get {
                return this.positionCodeField;
            }
            set {
                this.positionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PositionName {
            get {
                return this.positionNameField;
            }
            set {
                this.positionNameField = value;
            }
        }
        
        /// <remarks/>
        public string HomeAddress {
            get {
                return this.homeAddressField;
            }
            set {
                this.homeAddressField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string BankAccount {
            get {
                return this.bankAccountField;
            }
            set {
                this.bankAccountField = value;
            }
        }
        
        /// <remarks/>
        public string BankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        public string BankSwift_Code {
            get {
                return this.bankSwift_CodeField;
            }
            set {
                this.bankSwift_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string CardNo {
            get {
                return this.cardNoField;
            }
            set {
                this.cardNoField = value;
            }
        }
        
        /// <remarks/>
        public string DepartureDate {
            get {
                return this.departureDateField;
            }
            set {
                this.departureDateField = value;
            }
        }
        
        /// <remarks/>
        public string JoinDate {
            get {
                return this.joinDateField;
            }
            set {
                this.joinDateField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string BadList {
            get {
                return this.badListField;
            }
            set {
                this.badListField = value;
            }
        }
        
        /// <remarks/>
        public string ReasonOfBadList {
            get {
                return this.reasonOfBadListField;
            }
            set {
                this.reasonOfBadListField = value;
            }
        }
        
        /// <remarks/>
        public string DateQuit {
            get {
                return this.dateQuitField;
            }
            set {
                this.dateQuitField = value;
            }
        }
        
        /// <remarks/>
        public string DateUpdate {
            get {
                return this.dateUpdateField;
            }
            set {
                this.dateUpdateField = value;
            }
        }
        
        /// <remarks/>
        public string WorkPlaceName {
            get {
                return this.workPlaceNameField;
            }
            set {
                this.workPlaceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetListProfileCompletedEventHandler(object sender, GetListProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HREmpInfoBean[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HREmpInfoBean[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetListProfileThaCoCompletedEventHandler(object sender, GetListProfileThaCoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListProfileThaCoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListProfileThaCoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HREmpInfoBean[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HREmpInfoBean[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591